version: "3" # docker-compose version
services: # services which our app going to use. (list of containers we want to create)
  mongo_db: # container database name
    image: mongo:latest # On which image container will build
    restart: always
    volumes:
      - mongo_db:/data/db # path
    ports:
      - "27017:27017"
    
    
  api-server:
    build: .
    image: shop:0.0.2
    env_file: ./.env
    ports:
      - "9000:3000"
    environment:
      DB_HOST: localhost
      DB_NAME: expressTest
      DB_PORT: 27017
      DB_URL: mongodb://mongo_db:27017/expressTest # change DB_HOST --> container database name
    depends_on:
      - mongo_db

volumes:
  mongo_db: {}